[package]
name = "suricatax-ndpi-plugin"

# We're playing with versions here, not really sure how to make it work.
# - Suricata 8.0, plugin version 24 for nDPI 5.0
version = "8.0.24+ndpi5.0"

edition = "2021"
rust-version = "1.75.0"
description = "Suricata 8.0.x nDPI 5 plugin"
license = "GPL-2.0-only"
readme = "README.md"
publish = false
build = "build.rs"

[workspace]
members = [".", "ndpi-sys"]

[lib]
name = "ndpi"
crate-type = ["cdylib"]

[dependencies]
ndpi-sys = { version = "5.0.0", path = "ndpi-sys" }
serde_json = "1.0"
suricatax80-plugin-utils = { version = "0.1.0" }
